### ISSUE TITLE
truncated case

### ISSUE THREAD

**Issue by lfydegithub** [SuperMHP/GUPNet#10]
```python
depth_geo = size_3d[:,0]/box2d_height.squeeze()*roi_calibs[:,0,0]
```
当截断时, 例如公交/卡车, 此时box2d_height和实际的投影高度差挺多的, 网络能泛化出来吗?

**Comment by SuperMHP** [comment]
截断时train target仍然是box高度，这种情况下虽然depth推测不准，但是bias可以补回来

**Comment by lfydegithub** [comment]
> 

这里的`bias`是指下面的这个吗
```python
1. / (depth_net_out[:,0:1].sigmoid() + 1e-6) - 1.
```

**Comment by lfydegithub** [comment]
就是还有2个疑问
1. multi-bin的监督方式和smoke里那样的roty监督方式, 哪个更好呢
2. 使用roi的方式进行depth, roty的预测, 会不会比较"局部"?  那种直接预测的方式(one-stage)你们应该试验过, 是不好吗?

**Comment by SuperMHP** [comment]
1-1. bias是你说的那个
2-1. 你可以尝试roty比较下
2-2. 加入了coord map，并不会很局部，且local feature的感受野并不小。one stage会性能弱一些

**Comment by SuperMHP** [comment]
multibin在baseline上的更多信息可以参考原文deep3dbox：
https://arxiv.org/abs/1612.00496
