### ISSUE TITLE
why not h3d_std * X + h3d_mean ?

### ISSUE THREAD

**Issue by lfydegithub** [SuperMHP/GUPNet#11]
https://github.com/SuperMHP/GUPNet/blob/f4e26601ba5551065c36ab7ecf17f6915015d311/code/lib/models/gupnet.py#L165
according to 
![image](https://user-images.githubusercontent.com/29767851/148347089-5a91fd3c-bb74-4ba7-9049-cce601599666.png)
h3d should be equal to 
```python
h3d = self.mean_size[cls_ids[mask].long()] + size3d_offset * h3d_std
```
thx

**Comment by SuperMHP** [comment]
Please note that the code here: 
h3d in the code here is the $\mu_h$ in the paper, NOT the $h_{3d}$ distribution.

**Comment by lfydegithub** [comment]
according to:
code/lib/datasets/kitti.py line 219:
**size_3d[i] = src_size_3d[i] - mean_size**
and
code/lib/models/gupnet.py line 165:
**size_3d = (self.mean_size[cls_ids[mask].long()]+size3d_offset)**
it means that the network predict dim_offset and size_3d[0] is the real/final h3d.
my fist question *why not h3d_std * X + h3d_mean?* is wrong. my bad. 
wo de guo.
