### ISSUE TITLE
why not the bias depth is a negative number?

### ISSUE THREAD

**Issue by lfydegithub** [SuperMHP/GUPNet#12]
`bias_depth = 1. / (depth_net_out[:,0:1].sigmoid() + 1e-6) - 1.` ∈(0, +inf)
the bias_depth need be negative number if the geo_depth was bigger than real_depth.

**Comment by SuperMHP** [comment]
it is right. Because we use box 2d height as h2d, so the projection depth will be smaller than targets. So the bias should be also larger than zero.

**Comment by llwc** [comment]
Hello, I have a question about bias_depth = 1. / (depth_net_out[:,0:1].sigmoid() + 1e-6) - 1?  what is the difference with using bias_depth = exp(-depth_net_out[:,0:1])? Another question, this bias_depth cannot fixed the depth error if the bbox 2d height is smaller than its expected. Thanks!

**Comment by SuperMHP** [comment]
> Hello, I have a question about bias_depth = 1. / (depth_net_out[:,0:1].sigmoid() + 1e-6) - 1? what is the difference with using bias_depth = exp(-depth_net_out[:,0:1])? Another question, this bias_depth cannot fixed the depth error if the bbox 2d height is smaller than its expected. Thanks!

1). It is equal. This is provided by our baseline code implementation. 
2). The reason of bias>0 can be seen at the answer before your question.
