### ISSUE TITLE
Question about the Calibration.flip

### ISSUE THREAD

**Issue by yfthu** [SuperMHP/GUPNet#13]
Hello, you have done a great job!
I am some confused about the lib.datasets.kitti_utils.Calibration.flip function, which is used in your kitti dataloader. I am not sure about its function and result. when I try to use the flipped calib to back project some points from fliped image to the camera coordinate, I got very wrong result. 
I wonder the lib.datasets.kitti_utils.Calibration class is written by yourself or referenced from some orther codebase, Thank you very much!!!
Thanks!

**Comment by SuperMHP** [comment]
It is written by myself. I have tested several samples and gotten the right results. It should be right. The check pipeline is: flip 2d and 3d points both. And project 3d points by flipped calib file. The results should be equal to flipped 2d.

**Comment by yfthu** [comment]
Thank you very much for your answer!
