### ISSUE TITLE
Why does the loss become nan?

### ISSUE THREAD

**Issue by Cc-Hy** [SuperMHP/GUPNet#17]
Hello, during my training, the loss would always become nan, does anyone know why is it?
![image](https://user-images.githubusercontent.com/82150240/155830461-9e9c2286-eaac-49e0-89e2-13a121e3af24.png)

**Comment by SuperMHP** [comment]
it is anomaly. I have not meet that because the code of segloss comes from the centernet. I advise you to check the environment and the GPUs. Also, some times, the communication between different gpu breaks. It will also lead to nan for the torch program

**Comment by Cc-Hy** [comment]
Hello, I fixed the bug of nan.
But I find a new strange thing, that is, when I use the well-trained epoch to infer on the train set,
the AP is extremely low.
This is very strange, is there any bugs in the target building or output decoding?
I try to find out why is this, but failed.
Any idea?

**Comment by dingmiaomiao** [comment]
> Hello, I fixed the bug of nan. But I find a new strange thing, that is, when I use the well-trained epoch to infer on the train set, the AP is extremely low. This is very strange, is there any bugs in the target building or output decoding? I try to find out why is this, but failed. Any idea?

Hi, I have the same problem. the loss would always become nan. how did you solve this problem ？

**Comment by Cc-Hy** [comment]
> > Hello, I fixed the bug of nan. But I find a new strange thing, that is, when I use the well-trained epoch to infer on the train set, the AP is extremely low. This is very strange, is there any bugs in the target building or output decoding? I try to find out why is this, but failed. Any idea?
> 
> Hi, I have the same problem. the loss would always become nan. how did you solve this problem ？

My problem was caused by an incorrect function I wrote myself.
If you are using the original code without modification, I think your problem should be the batch size.

**Comment by SuperMHP** [comment]
Hi, I was busy with another deadline before. It is an easy way for you to check. You can download my released ckp (trained on train set) and infer it on eval set and train set both.
