### ISSUE TITLE
 evaluation scripts?

### ISSUE THREAD

**Issue by dingmiaomiao** [SuperMHP/GUPNet#18]
Thansks for your work, could you give me a evaluation scripts of AP40? I don't know where to download it?

**Comment by SuperMHP** [comment]
Hi, we have provided in here: 
g++ evaluate_object_3d_offline_apXX.cpp -o evaluate_object_3d_offline_ap
../../tools/kitti_eval/evaluate_object_3d_offline_apXX KITTI_LABEL_DIR ./output

You just need to set XX in evaluate_object_3d_offline_apXX as 40. For example:
g++ evaluate_object_3d_offline_ap40.cpp -o evaluate_object_3d_offline_ap40
../../tools/kitti_eval/evaluate_object_3d_offline_ap40 KITTI_LABEL_DIR ./output
