### ISSUE TITLE
Questions about evaluate results

### ISSUE THREAD

**Issue by Senwang98** [SuperMHP/GUPNet#20]
HI, @SuperMHP 
Thanks for your codes!
When evaluate the mAP|40, I use the cpp script you provided to get results.
As is shown in the following figure, I wonder what is the difference between `car_detection_ground` and `car_detection`?
![image](https://user-images.githubusercontent.com/23122139/162614326-ad5cf450-f94e-48dd-9e5d-850d02e2511f.png)

**Comment by Senwang98** [comment]
@SuperMHP 
By the way, I found my training log is strange.
After few epochs, the size3d_loss became negative：
![image](https://user-images.githubusercontent.com/23122139/162625675-43f80337-65d5-4905-918a-0669ff443d0b.png)

**Comment by SuperMHP** [comment]
1. One should be BEV result and another is 3D det result.

**Comment by SuperMHP** [comment]
2. The uncertainty loss could be negative. It is right
