### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by chenqiuli0** [SuperMHP/GUPNet#22]
Thanks for your work! I try to implement your code on windows but I have some problems in the process
![QQ截图20220524073236](https://user-images.githubusercontent.com/106123694/169921150-be04c710-d133-42cd-b3c5-808471d26b4b.png)

**Comment by SuperMHP** [comment]
It should be the pytorch cannot download the pretraining model on imagenet. The internet problem usually causes it.
