### ISSUE TITLE
i was wonder how to use evaluate code 

### ISSUE THREAD

**Issue by zzylovexx** [SuperMHP/GUPNet#29]
i use the evaluate code you provide but got an error below ,did anyone meet this issiue before,and how to fix it

Thank you for participating in our evaluation!
Loading detections...
number of files for evaluation: 3769
ERROR: Couldn't read: 005218.txt of ground truth. Please write me an email!
An error occured while processing your results.

**Comment by SuperMHP** [comment]
Hi， Have you downloaded all test or eval set files? Two things you can check:
1) In the dataset directory, do you have 005218.txt?
2) Please check the provided eval set directory in the evaluation script.
