### ISSUE TITLE
size3d_loss是负数

### ISSUE THREAD

**Issue by yjy4231** [SuperMHP/GUPNet#30]
您好，复现您的代码时发现size3d_loss后面一直是负数，这个会有影响吗？为什么会出现负数的情况？

**Comment by SuperMHP** [comment]
正常的，log_var可以为负值在 2023年5月22日，14:22，yjy4231 ***@***.***> 写道：﻿
您好，复现您的代码时发现size3d_loss后面一直是负数，这个会有影响吗？为什么会出现负数的情况？
