### ISSUE TITLE
关于实验可重复性的问题

### ISSUE THREAD

**Issue by wzichen294** [SuperMHP/GUPNet#37]
我使用相同的训练参数配置在多次实验中都获得了不同的实验结果，代码没有被修改，请问该如何解决这种情况

**Comment by SuperMHP** [comment]
抖动对于验证集这是正常的，通常在处理验证集的时候，我自己会做10次左右实验取最佳结果。对于测试集，由于评估在线上，则不能多次取最佳，跑一次即可，paper的结果为随机一次的结果在 2023年12月16日，16:06，Zichen Wang ***@***.***> 写道：﻿
我使用相同的训练参数配置在多次实验中都获得了不同的实验结果，代码没有被修改，请问该如何解决这种情况
