### ISSUE TITLE
The scale augmentation is not suitable for 3d regression

### ISSUE THREAD

**Issue by VincentZ-2020** [SuperMHP/GUPNet#38]
when randomcrop happends, gupnet still regress 3d information.Is it a bug?

**Comment by SuperMHP** [comment]
It is not a bug. The gupnet has a coordinate map for each ROI. This provides absolute scale information for features, making the model suitable for randomcropping aug.

**Comment by VincentZ-2020** [comment]
I have readed  the codes of coord maps.It's a novel operation!
