### ISSUE TITLE
Much lower AP_3D compared to AP_BEV

### ISSUE THREAD

**Issue by SPengLiang** [SuperMHP/GUPNet#4]
Thanks for your great work!

I use the released code to retrain the network, while the results are strange.
I obtain: 
bev@0.70 [29.223935810025136, 21.975801299792906, 19.0762136467218]
3d@0.70 [17.863160821111062, 12.961739635817185, 10.802839248636912]

where the AP_BEV is OK, but the AP_3D is considerably low.  I tried three times and get similar results.

**Comment by SuperMHP** [comment]
你好，这是我昨天又跑了三组的结果，结果如下：
BEV: 29.59, 21.00, 18.71
3D: 21.63, 15.43, 13.02

BEV: 28.79, 20.61, 17.48
3D: 21.51, 15.36, 12.79

BEV: 26.92, 19.87, 16.85
3D: 20.10, 14.08, 12.04

最差的随机结果是最后一组。并没有遇到你的问题，然后我们在另一组机器上也试了，也正常。
我不太确定是不是环境问题以及一些包的配置导致的，你可以按照我readme上新更新的环境配置过程从头配下

**Comment by Senwang98** [comment]
@SPengLiang 
哈喽，请问一下GUPNet你能训到mAP16嘛，训练3次都小于15.50，竟然能有这么大jitter。。。。

**Comment by SPengLiang** [comment]
> @SPengLiang 哈喽，请问一下GUPNet你能训到mAP16嘛，训练3次都小于15.50，竟然能有这么大jitter。。。。 我记得老哥的DID-M3D也是基于GUPNet，似乎没那么大训练波动。

具体的有点记不太清了，我记得gupnet训出来的AP和上面作者老哥回复的差不多，差不多是15点几的样子

**Comment by Senwang98** [comment]
@SPengLiang 
嗯嗯，了解了，谢谢啦
