### ISSUE TITLE
Which script  should be used for evaluation in tools? ap11 ? or ap40? 

### ISSUE THREAD

**Issue by lji72** [SuperMHP/GUPNet#8]

**Comment by lji72** [comment]
Which script should be used for evaluation in tools? ap11 ? or ap40? 
Which one is used in the paper report?

**Comment by SuperMHP** [comment]
Hi, ap40 is the paper and released checkpoint performances metric.

**Comment by lji72** [comment]
Thanks！

**Comment by dingmiaomiao** [comment]
Thansks for your work, could you give me a evaluation tools of AP40? I don't know how to download it?
